brew "mkcert"
brew "fzf"
brew "ghq"
brew "stow"
brew "starship"
brew "zsh-completions"

cask "notion"
cask "slack"
cask "visual-studio-code"
cask "discord"
cask "scroll-reverser"
cask "karabiner-elements"